name: Dev CLI

on:
  push:
    branches:
      - dev
  pull_request:
      - dev
      
env:
  EXILED_REFERENCES_URL: https://exiled.host/build_deps/Dev.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References
 
