name: NukeLock Dev CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: [windows-latest]
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Marco15453/AutoNuke'
    
    steps:
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@master
      
      - name: Setup NuGet
        uses: iRebbok/setup-nuget@master
        
      - name: Get Repositories
        uses: actions/checkout@v2
        
      - name: Restore NuGet packages
        run: nuget restore NukeLock.sln
        
      - name: Build
        run: msbuild NukeLock.sln
